version: '3.7'


services:
  web:
    build: .
    command: bash -c "python manage.py migrate --no-input &&
      python manage.py loaddata fixtures/product.json fixtures/category.json &&
      python manage.py runserver"
    ports:
      - "8000:8000"
    links:
      - redis:redis
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
