# Generated by Django 3.2.13 on 2022-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
