# Generated by Django 3.2.13 on 2022-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
