# Generated by Django 3.2.13 on 2022-07-30 18:45

import django.db.models.deletion
from django.db import migrations, models

import products.utils


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.utils.upload_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', blank=True,
                                    null=True),
            preserve_default=False,
        ),
    ]
